// <auto-generated />
using Conference.Infrastructure.Persistence.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Conference.Infrastructure.Migrations
{
    [DbContext(typeof(ConferenceDbContext))]
    partial class ConferenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Conference.Infrastructure.Persistence.DatabaseModels.Attendee", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Attendee__3214EC07C2DE7C16");

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("Conference.Infrastructure.Persistence.DatabaseModels.Conference", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Conferen__3214EC0729567E61");

                    b.ToTable("Conferences");
                });

            modelBuilder.Entity("Conference.Infrastructure.Persistence.DatabaseModels.Order", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ConferenceId")
                        .HasColumnType("int");

                    b.Property<int>("SeatsQuantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Orders__3214EC0714DFF511");

                    b.HasIndex("ConferenceId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Conference.Infrastructure.Persistence.DatabaseModels.SeatsAvailability", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ConferenceId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__SeatsAva__3214EC0719E8A284");

                    b.HasIndex("ConferenceId");

                    b.ToTable("SeatsAvailability", (string)null);
                });

            modelBuilder.Entity("OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("AttendeeId")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "AttendeeId")
                        .HasName("Pk_OrderItems");

                    b.HasIndex("AttendeeId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("Conference.Infrastructure.Persistence.DatabaseModels.Order", b =>
                {
                    b.HasOne("Conference.Infrastructure.Persistence.DatabaseModels.Conference", "Conference")
                        .WithMany("Orders")
                        .HasForeignKey("ConferenceId")
                        .IsRequired()
                        .HasConstraintName("Fk_Orders_Conferences_ConferenceId");

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("Conference.Infrastructure.Persistence.DatabaseModels.SeatsAvailability", b =>
                {
                    b.HasOne("Conference.Infrastructure.Persistence.DatabaseModels.Conference", "Conference")
                        .WithMany("SeatsAvailabilities")
                        .HasForeignKey("ConferenceId")
                        .IsRequired()
                        .HasConstraintName("Fk_SeatsAvailability_Conferences_ConferenceId");

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("OrderItem", b =>
                {
                    b.HasOne("Conference.Infrastructure.Persistence.DatabaseModels.Attendee", null)
                        .WithMany()
                        .HasForeignKey("AttendeeId")
                        .IsRequired()
                        .HasConstraintName("Fk_OrderItems_Attendees_AttendeeId");

                    b.HasOne("Conference.Infrastructure.Persistence.DatabaseModels.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("Fk_OrderItems_Orders_OrderId");
                });

            modelBuilder.Entity("Conference.Infrastructure.Persistence.DatabaseModels.Conference", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("SeatsAvailabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
